# Generated by Django 5.2.6 on 2025-11-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perfumeria', '0002_cliente_empleado_cliente_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='producto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='app_perfumeria.producto'),
        ),
    ]
