# Generated by Django 5.2.6 on 2025-11-11 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perfumeria', '0003_remove_cliente_producto_cliente_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='empleado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='empleados',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='app_perfumeria.empleado'),
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='app_perfumeria.cliente')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='app_perfumeria.empleado')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
