# Generated by Django 5.2.6 on 2025-11-12 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perfumeria', '0004_remove_cliente_productos_remove_cliente_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='empleados',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='empleado',
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='empleados',
            field=models.ManyToManyField(related_name='ventas_asociadas', to='app_perfumeria.empleado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(default='Sin puesto', max_length=100),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='cliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app_perfumeria.cliente'),
            preserve_default=False,
        ),
    ]
