# Generated by Django 5.2.6 on 2025-11-12 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perfumeria', '0006_remove_cliente_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_atendidos', to='app_perfumeria.empleado'),
        ),
    ]
