# Generated by Django 5.2.6 on 2025-11-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perfumeria', '0007_cliente_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
