# Generated by Django 5.2.6 on 2025-11-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perfumeria', '0008_remove_cliente_ciudad_cliente_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
