# Generated by Django 5.2.6 on 2025-11-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perfumeria', '0010_proveedor_producto_pedidoproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='pagina_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
